### ISSUE TITLE
Error installing script Windows env - VueCharts

### ISSUE THREAD

**Issue by DanyHubGit** [copper-engine/copper-monitoring#1]
I have launched the command
**start.cmd --install**

but, after having resolved all npm dependencies, the script has the following error

**ERROR in [at-loader] ./src/components/dashboard/overview/stats/stats.ts:3:10
    TS2305: Module '"<path>/copper-monitoring/client/node_modules/vue-chartjs/types/index"' has no exported member 'VueCharts'.**

I'm trying to install the monitoring gui in **windows 10 environment**.

Do you suggest me anything to check?
Thanks in advance

**Comment by HaydenHodge** [comment]
Hello DanyHubGit, thanks for posting the issue. It is fixed! 
After looking into it, the issue stems from some incompatibility with the most recently released version of VueChart.js. I was able to recreate the issue by using version 3.4.0. I made some changes and ran the same command you mentioned myself in a Windows 10 environment to verify the fix. 
The most recent version of the master branch contains the changes you need.
Thanks!

**Comment by DanyHubGit** [comment]
Issue resolved. Thanks
