### ISSUE TITLE
Unnable to connect

### ISSUE THREAD

**Issue by DanyHubGit** [copper-engine/copper-monitoring#2]
I have created a very simple Java application to test a simple workflow.
The workflow starts and ends without any problem, but on monitoring UI I have always the same error "**Unnable to connect**" (with double n :) )

In my Java application I have referenced 
_-copper-copperengine 5.0.1.jar
-copper-jmx-interface5.0.1.jar
-copper-monitoring-client4.2.0.jar
-copper-monitoring-core4.2.0.jar_

and I have set the following VM parameter in run configuration 

_-Dcom.sun.management.jmxremote=true 
-Dcom.sun.management.jmxremote.authenticate=false 
-Dcom.sun.management.jmxremote.port=1099 
-Dcom.sun.management.jmxremote.ssl=false_ 

But I have always the same issue.
It's possible to add a verbose log to understand why the GUI is in "unable to connect" state?

Is there any reference to add to Java application?
Is there anything to instrument in my java code?
Can you suggest me a checklist to understand how to resolve my issue?

Thanks in advance

![image](https://user-images.githubusercontent.com/6823617/45813962-5b8f3280-bcd4-11e8-8482-24e6cfa4ebac.png)

**Comment by HaydenHodge** [comment]
Hello DanyHubGit. I would suggest figuring out where the communication breakdown is occurring. The best way to start would be by making sure your Java application has an exposed port with properly registered mbeans. Try testing that with JConsole, and making sure you can see your application's engines, processor pools, etc. 

![image](https://user-images.githubusercontent.com/36037542/45940492-b5943e80-bfd9-11e8-85bc-e121665c0072.png)

**Comment by DanyHubGit** [comment]
Thank you for your suggestions, there was an issue in my mbeans declarations.

**Comment by HaydenHodge** [comment]
No problem at all, I'm glad I could help!
